name: GCSim CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install clang 21
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release cmake make

          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21

          clang++-21 --version

      - name: Build GoogleTest
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest

          cmake -B build -DCMAKE_CXX_COMPILER=clang++-21
          cmake --build build -j$(nproc)

          sudo cmake --install build

      - name: Build simulator
        run: |
          make -j$(nproc) \
            CXX=clang++-21

      - name: Run tests
        run: |
          make test -j$(nproc) \
            CXX=clang++-21